-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    full_name text not null,
    role text not null check (role in ('artisan', 'buyer')),
    craft_specialty text,
    location text,
    created_at timestamptz not null default now()
);

-- Add profile fields when upgrading an older profiles table.
alter table public.profiles add column if not exists full_name text;
alter table public.profiles add column if not exists role text;
alter table public.profiles add column if not exists craft_specialty text;
alter table public.profiles add column if not exists location text;
alter table public.profiles add column if not exists profile_image_url text;
alter table public.profiles add column if not exists story text;
alter table public.profiles add column if not exists created_at timestamptz default now();

create table if not exists public.products (
    id bigint generated by default as identity primary key,
    artisan_id uuid not null references public.profiles(id) on delete cascade,
    title text not null,
    category text not null,
    price numeric not null check (price >= 0),
    image_url text,
    image_urls jsonb not null default '[]'::jsonb,
    description text,
    created_at timestamptz not null default now()
);

alter table public.products add column if not exists image_urls jsonb not null default '[]'::jsonb;

create table if not exists public.wishlists (
    id bigint generated by default as identity primary key,
    buyer_id uuid not null references public.profiles(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (buyer_id, product_id)
);

create table if not exists public.cart_items (
    id bigint generated by default as identity primary key,
    buyer_id uuid not null references public.profiles(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    quantity integer not null default 1 check (quantity > 0),
    created_at timestamptz not null default now(),
    unique (buyer_id, product_id)
);

create table if not exists public.orders (
    id bigint generated by default as identity primary key,
    buyer_id uuid not null references public.profiles(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    quantity integer not null default 1 check (quantity > 0),
    total_price numeric not null check (total_price >= 0),
    status text not null default 'pending' check (status in ('pending', 'confirmed', 'shipped', 'delivered', 'cancelled')),
    created_at timestamptz not null default now()
);

create table if not exists public.product_reviews (
    id bigint generated by default as identity primary key,
    buyer_id uuid not null references public.profiles(id) on delete cascade,
    product_id bigint not null references public.products(id) on delete cascade,
    rating integer not null check (rating between 1 and 5),
    review text not null,
    created_at timestamptz not null default now(),
    unique (buyer_id, product_id)
);

alter table public.profiles enable row level security;
alter table public.products enable row level security;
alter table public.wishlists enable row level security;
alter table public.cart_items enable row level security;
alter table public.orders enable row level security;
alter table public.product_reviews enable row level security;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
    insert into public.profiles (id, full_name, role, craft_specialty, location, profile_image_url, story)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'full_name', ''),
        coalesce(new.raw_user_meta_data ->> 'role', 'buyer'),
        new.raw_user_meta_data ->> 'specialty',
        new.raw_user_meta_data ->> 'location',
        new.raw_user_meta_data ->> 'profile_image_url',
        new.raw_user_meta_data ->> 'story'
    )
    on conflict (id) do update set
        full_name = excluded.full_name,
        role = excluded.role,
        craft_specialty = excluded.craft_specialty,
        location = excluded.location,
        profile_image_url = excluded.profile_image_url,
        story = excluded.story;
    return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

-- Backfill profiles for Auth users created before this trigger existed.
insert into public.profiles (id, full_name, role, craft_specialty, location, profile_image_url, story)
select
    id,
    coalesce(raw_user_meta_data ->> 'full_name', ''),
    case when raw_user_meta_data ->> 'role' = 'artisan' then 'artisan' else 'buyer' end,
    raw_user_meta_data ->> 'specialty',
    raw_user_meta_data ->> 'location',
    raw_user_meta_data ->> 'profile_image_url',
    raw_user_meta_data ->> 'story'
from auth.users
on conflict (id) do update set
    full_name = excluded.full_name,
    role = excluded.role,
    craft_specialty = excluded.craft_specialty,
    location = excluded.location,
    profile_image_url = excluded.profile_image_url,
    story = excluded.story;

drop policy if exists "Public can view profiles" on public.profiles;
create policy "Public can view profiles"
    on public.profiles for select using (true);

drop policy if exists "Users can update their profile" on public.profiles;
create policy "Users can update their profile"
    on public.profiles for update using (auth.uid() = id);
drop policy if exists "Users can create their profile" on public.profiles;
create policy "Users can create their profile"
    on public.profiles for insert with check (auth.uid() = id);

drop policy if exists "Public can view products" on public.products;
create policy "Public can view products"
    on public.products for select using (true);

drop policy if exists "Artisans can publish products" on public.products;
create policy "Artisans can publish products"
    on public.products for insert
    with check (
        auth.uid() = artisan_id
        and exists (
            select 1 from public.profiles
            where id = auth.uid() and role = 'artisan'
        )
    );

drop policy if exists "Artisans can delete their products" on public.products;
create policy "Artisans can delete their products"
    on public.products for delete
    using (auth.uid() = artisan_id);

drop policy if exists "Buyers can view their wishlists" on public.wishlists;
create policy "Buyers can view their wishlists" on public.wishlists for select using (auth.uid() = buyer_id);
drop policy if exists "Buyers can add wishlists" on public.wishlists;
create policy "Buyers can add wishlists" on public.wishlists for insert with check (auth.uid() = buyer_id);
drop policy if exists "Buyers can remove wishlists" on public.wishlists;
create policy "Buyers can remove wishlists" on public.wishlists for delete using (auth.uid() = buyer_id);

drop policy if exists "Buyers can view their cart" on public.cart_items;
create policy "Buyers can view their cart" on public.cart_items for select using (auth.uid() = buyer_id);
drop policy if exists "Buyers can add cart items" on public.cart_items;
create policy "Buyers can add cart items" on public.cart_items for insert with check (auth.uid() = buyer_id);
drop policy if exists "Buyers can update their cart" on public.cart_items;
create policy "Buyers can update their cart" on public.cart_items for update using (auth.uid() = buyer_id);
drop policy if exists "Buyers can remove cart items" on public.cart_items;
create policy "Buyers can remove cart items" on public.cart_items for delete using (auth.uid() = buyer_id);

drop policy if exists "Buyers can view their orders" on public.orders;
create policy "Buyers can view their orders" on public.orders for select using (auth.uid() = buyer_id);
drop policy if exists "Buyers can create orders" on public.orders;
create policy "Buyers can create orders" on public.orders for insert with check (auth.uid() = buyer_id);

drop policy if exists "Everyone can view reviews" on public.product_reviews;
create policy "Everyone can view reviews" on public.product_reviews for select using (true);
drop policy if exists "Buyers can create reviews" on public.product_reviews;
create policy "Buyers can create reviews" on public.product_reviews for insert with check (auth.uid() = buyer_id);
drop policy if exists "Buyers can update reviews" on public.product_reviews;
create policy "Buyers can update reviews" on public.product_reviews for update using (auth.uid() = buyer_id);
drop policy if exists "Buyers can delete reviews" on public.product_reviews;
create policy "Buyers can delete reviews" on public.product_reviews for delete using (auth.uid() = buyer_id);

-- Product image storage. The bucket is public so marketplace images can be displayed.
insert into storage.buckets (id, name, public)
values ('product-images', 'product-images', true)
on conflict (id) do update set public = true;

insert into storage.buckets (id, name, public)
values ('profile-images', 'profile-images', true)
on conflict (id) do update set public = true;

drop policy if exists "Authenticated users can upload product images" on storage.objects;
create policy "Authenticated users can upload product images"
    on storage.objects for insert to authenticated
    with check (
        bucket_id = 'product-images'
    );

drop policy if exists "Public can view product images" on storage.objects;
create policy "Public can view product images"
    on storage.objects for select to public
    using (bucket_id = 'product-images');

drop policy if exists "Authenticated users can upload profile images" on storage.objects;
create policy "Authenticated users can upload profile images"
    on storage.objects for insert to authenticated
    with check (bucket_id = 'profile-images' and (storage.foldername(name))[1] = auth.uid()::text);

drop policy if exists "Public can view profile images" on storage.objects;
create policy "Public can view profile images"
    on storage.objects for select to public
    using (bucket_id = 'profile-images');

drop policy if exists "Artisans can delete their product images" on storage.objects;
create policy "Artisans can delete their product images"
    on storage.objects for delete to authenticated
    using (bucket_id = 'product-images' and (storage.foldername(name))[1] = auth.uid()::text);